# This uses daemitus workflows.

name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on: 
  workflow_dispatch:
    branches:
    - master

env:
  SOLUTION_NAME: LeaveDutyCmdPlugin
  INTERNAL_NAME: LeaveDutyCmdPlugin
  RELEASE_DIR: LeaveDutyCmdPlugin\bin\Release\LeaveDutyCmdPlugin

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"   
    - name: Build
      run: |
        dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
        dotnet build --configuration Release
      env: 
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: ${{ env.RELEASE_DIR }}
        if-no-files-found: error
